apiVersion: v1
kind: Service
metadata:
  name: operation-service
  labels:
    app: operation-service
spec:
  selector:
    app: operation-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: operation-service-lb
  labels:
    app: operation-service
spec:
  selector:
    app: operation-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP
  type: LoadBalancer